### ISSUE TITLE
Error on plugin enable

### ISSUE THREAD

**Issue by Xenophilicy** [JackNoordhuis/DiscordRelay-PocketMine#2] opened 2019-02-11 05:57 UTC
I got two different errors while enabling the latest release of your plugin as well as running your earlier one.

**OS: Windows**
**PMMP Version: v3.6.1**
**Plugin Version(s): v0.0.2-ALPHA & v0.0.1-ALPHA**

***
### Here is the first one
```
[23:50:24] [Server thread/CRITICAL]: RuntimeException: "Tried to register a relay channel twice!" (EXCEPTION) in "plugins/DiscordRelay/src/jacknoordhuis/discordrelay/models/RelayOptions" at line 87
```
### Here is the second one
```
[23:50:24] [Server thread/CRITICAL]: Error: "Call to a member function getTaskId() on null" (EXCEPTION) in "plugins/DiscordRelay/src/jacknoordhuis/discordrelay/DiscordRelay" at line 78
```

Hope to hear back soon! I look forward to using your plugin!

**Comment by JackNoordhuis** [comment] 2019-02-12 06:35
The first error is caused by the plugin attempting to load it's default configuration files. Make sure you set up the plugin: https://github.com/JackNoordhuis/DiscordRelay-PocketMine/wiki/Configuring. The second error is caused as the plugin failed to start and then pocketmine attempts to disable it, this should never happen if the plugin loads the configuration correctly.

**Comment by Xenophilicy** [comment] 2019-02-12 08:47
Thanks for the response, sadly I ran into another error when the plugin is enabling. Please see the attached code at the bottom to view my configuration file.
***
### Error report:
```
[02:37:11] [Server thread/CRITICAL]: RuntimeException: "Tried to register a relay channel twice!" (EXCEPTION) in "plugins/DiscordRelay/src/jacknoordhuis/discordrelay/models/RelayOptions" at line 87
```
I also got the second error again, but I assume that will disappear once we get this working.
***
### Settings file:
```yaml
###  Discord-Relay v0.0.2-ALPHA configuration file  ###
general:
  # The default channel messages are relayed to and from discord.
  # Will respect both relay-from-discord and relay-to-discord flags (can be set to only relay one way.)
  default-channel: 
  bot:
    token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  channels:
    - name: lobby-chat
      discord-id: 544790094461272065
      embed-color: 16771072
      options:
        embed: true
        relay-from-discord: true
        relay-to-discord: true
    - name: lobby-logs
      discord-id: 544794898046517249
      options:
        relay-to-discord: true
        relay-from-discord: false
        embed: true
        console-levels:
          info:
            embed-color: 16777215 # White - Info
          notice:
            embed-color: 2612166 # Aqua - Notice
          debug:
            embed-color: 10743551 # Light Aqua - Debug
    - name: error-reports
      discord-id: 544791880420818964
      options:
        embed: true
        embed-color: 16721408
        relay-to-discord: true
        relay-from-discord: false
        console-levels: [emergency, alert, critical, error]
```

**Comment by JackNoordhuis** [comment] 2019-02-13 12:35
Are you modifying the correct config file? PocketMine now stores plugin configs in `/plugin_data`. Are you running from source or using the release phar?

**Comment by Xenophilicy** [comment] 2019-02-13 12:54
Yes of course I'm modifying the correct config, hence the error... Also there is no phar for `0.0.2-ALPHA`, only one for `0.0.1-ALPHA`, although neither of them work with my setup. See the image below for the path to my config file. I've also tried to delete the DiscordRelay folder in plugin_data and reenter my info, that gave me the same error as before, even with with the second release source code.
***
### Image:
![path](https://user-images.githubusercontent.com/44390060/52712949-b5321b00-2f5b-11e9-9e79-56b4cd125f30.PNG)


@JackNoordhuis Any update on how to fix this?

**Comment by JackNoordhuis** [comment] 2019-02-17 02:36
Your configuration works fine for me:
```
[13:28:27] [RelayThread thread/WARNING]: Unable to find channel #544790094461272065, a bridge will not be setup for this channel.
[13:28:27] [RelayThread thread/WARNING]: Unable to find channel #544794898046517249, a bridge will not be setup for this channel.
[13:28:27] [RelayThread thread/WARNING]: Unable to find channel #544791880420818964, a bridge will not be setup for this channel.
[13:28:28] [RelayThread thread/DEBUG]: Logged in as pocketmine-bridge#0617 created on 24.09.2017 22:53:30
```

Once the plugin is loading the correct configuration you'll run into an issue with the default channel being null, you should specify your lobby-chat channel as the default as the plugin currently only supports sending players in-game messages to one channel (default-channel).

Then you will most likely run into the same issues as described in #1 which is a pretty common problem so use google if the solution I provided doesn't work for you.

I'm going to close this issue for now unless you can give me some way of reproducing your problem on my machine. As dumb or annoying as it sounds it seems like the plugin is reading the wrong configuration file whether that is the fault of the plugin or not remains to be proven.

**Closed as completed by JackNoordhuis** 2019-02-17 02:36 UTC
Labels: invalid

**Comment by Xenophilicy** [comment] 2019-02-17 02:38
Ok thanks for the help.

**Comment by JackNoordhuis** [comment] 2019-02-17 02:44
I've just uploaded a compiled phar for the v0.0.2-ALPHA release as well. If you have any more questions or want help trying to debug the issue contact me on discord (`JackNoordhuis#0001`) or ask in the pocketmine discord (https://discord.gg/XDugAkJ).
